name: PRs

on:
  push:
    branches:
      - !main
      - '!**-build'

jobs:

  unittesting:
    runs-on: ubuntu-latest
    container:
      image: earthmancfy/unittesting:v9
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true
      - name: Git Submodule Update
        run: |
          git config --global --add safe.directory '*'
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Download stuff
        run: |
          git clone --depth 1 https://${GH_TOKEN}@github.com/fusion-e/fusion-common.git ${HOME}/fusion-common -b master
          git clone --depth 1 https://${GH_TOKEN}@github.com/fusion-e/fusion-agent.git ${HOME}/fusion-agent -b master
          git clone --depth 1 https://${GH_TOKEN}@github.com/fusion-e/fusion-manager.git ${HOME}/fusion-manager -b master
          git clone --depth 1 https://${GH_TOKEN}@github.com/fusion-e/nativeedge-plugins-sdk.git ${HOME}/nativeedge-plugins-sdk -b main
      - name: Update Git
        run: |
          git submodule init
          git submodule update --remote --recursive | true
      - name: Install tox
        run: pip install tox
      - name: Run Tests
        run: HOME=${HOME} VIRTUAL_ENV=${HOME}/.pyenv/${VENVS} tox